version: "3.8"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_todolist
    image: postgres:16
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  keycloak_todolist:
    container_name: keycloak_todolist
    image: jboss/keycloak:16.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"